import { techTags } from '../types/tag'

export const PROYECTS = [
    {
        title: 'SIMBig24 - Ilo',
        desc: 'SIMBig is one of the first conferences in Latin America grouping areas such as Artificial Intelligence, Machine Learning, Deep Learning, Healthcare Informatics, Natural Language Processing, Semantic Web, Software Engineering, among others. ',
        image: '/assets/images/proyects/1.png',
        tecnologies: [
            techTags.astro,
            techTags.express,
            techTags.tailwind,
            techTags.typescript,
            techTags.html,
            techTags.css,
            techTags.figma,
            techTags.vscode,
            techTags.vercel,
            techTags.posgresql,
            techTags.postman,
        ],
    },
    {
        title: 'CISCCOM - Ilo',
        desc: 'CISCCOM reúne a un conjunto diverso de profesionales, investigadores y estudiantes de diversas partes del mundo y de distintas etapas de sus carreras. Este ambiente propicia el encuentro y la conexión entre los asistentes e invitados para enriquecer sus redes profesionales y abrir puertas a futuras colaboraciones, proyectos conjuntos y oportunidades de empleo. ',
        image: '/assets/images/proyects/2.png',
        tecnologies: [
            techTags.tailwind,
            techTags.astro,
            techTags.figma,
            techTags.next,
            techTags.react,
            techTags.typescript,
            techTags.html,
            techTags.css,
            techTags.vercel,
            techTags.vscode,
            techTags.mongodb, techTags.postman
        ],
    },
    {
        title: 'Raymi Social - ILo',
        desc: 'Es una aplicación web que te permite compartir publicaciones, fotos y videos con tus amigos.',
        image: '/assets/images/proyects/3.png',
        tecnologies: [
            techTags.tailwind,
            techTags.figma,
            techTags.next,
            techTags.react,
            techTags.typescript,
            techTags.html,
            techTags.css,
            techTags.vercel,
            techTags.vscode,
            techTags.posgresql,
        ],
    },
    {
        title: 'Acortador de URL',
        desc: 'Es una aplicación web que te permite acortar URLs.',
        image: '/assets/images/proyects/4.png',
        tecnologies: [
            techTags.tailwind,
            techTags.figma,
            techTags.next,
            techTags.react,
            techTags.typescript,
            techTags.html,
            techTags.css,
            techTags.vercel,
            techTags.vscode,
            techTags.mysql,
        ],
    },
    {
        title: 'Grafos',
        desc: 'Es una aplicación web que te permite visualizar y crear grafos a partir de imágenes.',
        image: '/assets/images/proyects/5.png',
        tecnologies: [
            techTags.figma,
            techTags.react,
            techTags.typescript,
            techTags.html,
            techTags.css,
            techTags.vercel,
            techTags.vscode,
        ],
    },
    {
        title: 'Clinica Americana',
        desc: 'Es una aplicación web que permite administar una clinica dental tendiendo en consideracion odontogramas y citas.',
        image: '/assets/images/proyects/6.png',
        tecnologies: [
            techTags.tailwind,
            techTags.figma,
            techTags.next,
            techTags.react,
            techTags.typescript,
            techTags.html,
            techTags.css,
            techTags.vercel,
            techTags.vscode,
            techTags.posgresql,
            techTags.postman
        ],
    },
    {
        title: 'Colora.',
        desc: 'Es una aplicación web que te permite genera, exportar, copiar y compartir paletas de colores.',
        image: '/assets/images/proyects/7.png',
        tecnologies: [
            techTags.tailwind,
            techTags.figma,
            techTags.next,
            techTags.react,
            techTags.javascript,
            techTags.vercel,
            techTags.vscode,
        ],
    },
]
